let ctx,programs=[],templates=[],defaults={},record,previewURL;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=v=>String(v||'').replaceAll('_',' ');
const input=(name,label,value='',type='text',required=true,extra='')=>`<label class="nc-field"><span class="nc-label">${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${extra}></label>`;
const select=(name,label,options,value='')=>`<label class="nc-field"><span class="nc-label">${esc(label)}</span><select name="${name}">${options.map(o=>{const [v,l]=Array.isArray(o)?o:[o,pretty(o)];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`;}).join('')}</select></label>`;
const text=(name,label,value='',max=2000)=>`<label class="nc-field"><span class="nc-label">${esc(label)}</span><textarea name="${name}" maxlength="${max}">${esc(value)}</textarea></label>`;
const button=(label,action='',extra='')=>`<button class="nc-button secondary" type="button" data-admin-action="${action}" ${extra}>${esc(label)}</button>`;
const link=(label,url)=>`<a class="nc-button secondary" href="${esc(url)}">${esc(label)}</a>`;
const tag=v=>`<span class="nc-tag">${esc(pretty(v||'NOT ISSUED'))}</span>`;
const details=items=>`<dl class="nc-details">${items.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v||'Not provided')}</dd></div>`).join('')}</dl>`;
const date=v=>v?String(v).slice(0,10):'—';
const empty=label=>`<div class="nc-empty">${esc(label)}</div>`;
const sections=[['dashboard','Dashboard'],['internships/programs','Internship Programs'],['interns','Interns'],['applications','Applications'],['offers','Offer Letters'],['certificates','Certificates'],['templates','Templates'],['verification','Verification'],['company-assets','Company Assets'],['audit-logs','Audit Logs'],['settings','Settings']];
function shell(title,content){
  ctx.root.classList.add('nc-admin');
  ctx.root.innerHTML=`<div class="nc-admin-layout"><aside class="nc-sidebar"><a class="nc-admin-brand" href="/admin/dashboard">NEXTORA<span>COMPANY WORKSPACE</span></a><nav aria-label="Administration">${sections.map(([p,l])=>`<a href="/admin/${p}" ${location.pathname===`/admin/${p}`?'aria-current="page"':''}>${l}</a>`).join('')}</nav><button class="nc-link" data-action="logout">Logout</button></aside><div class="nc-admin-main"><div class="nc-topline"><p class="nc-eyebrow">Internship administration</p><span>${esc(ctx.session.user.email)}</span></div><h1 class="nc-admin-title">${esc(title)}</h1><div id="nc-message" role="status" aria-live="polite"></div>${content}</div></div>`;
}
const pagination=(count)=>{const q=new URLSearchParams(location.search),page=Number(q.get('page')||1);q.set('page',page-1);const prev=`${location.pathname}?${q}`;q.set('page',page+1);return `<div class="nc-actions">${page>1?link('Previous',prev):''}<span>Page ${page}</span>${count===25?link('Next',`${location.pathname}?${q}`):''}</div>`;};
function table(head,rows){return rows.length?`<div class="nc-table-wrap" tabindex="0" aria-label="Records; scroll horizontally"><table class="nc-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('No records yet.');}
function internTable(rows,full=false){return table(full?['Intern ID','Name / email','Phone','College / course','Program / role','Dates / duration','Status','Certificate','Offer','Actions']:['Intern','Program','Dates','Status','Record'],rows.map(i=>full?[esc(i.id),`<strong>${esc(i.full_name)}</strong><small>${esc(i.email)}</small>`,esc(i.phone_number),`${esc(i.college_name)}<small>${esc(i.course)}</small>`,`${esc(i.program_title)}<small>${esc(i.role)}</small>`,`${date(i.start_date)} – ${date(i.end_date)}<small>${i.minimum_duration_months} months minimum</small>`,tag(i.status),tag(i.certificate_status),tag(i.offer_status),link('View',`/admin/interns/${i.id}`)]:[esc(i.full_name),esc(i.program_title),`${date(i.start_date)} – ${date(i.end_date)}`,tag(i.status),link('Open',`/admin/interns/${i.id}`)]));}
function programForm(p={}) {return `<form class="nc-form nc-panel" data-admin-form="program" data-id="${esc(p.id||'')}"><h2>${p.id?'Edit program':'Create program'}</h2><div class="nc-form-grid">${input('title','Program name',p.title,'text',true,'maxlength="120"')}${input('slug','Slug',p.slug,'text',true,'pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="140"')}${input('department','Department',p.department)}${input('role','Role',p.role||'Intern')}${input('duration_months','Duration (months)',p.duration_months||3,'number',true,'min="1" max="60"')}${input('minimum_duration_months','Minimum duration (months)',p.minimum_duration_months||3,'number',true,'min="1" max="60"')}${input('start_date','Start date',p.start_date,'date',false)}${input('end_date','End date',p.end_date,'date',false)}${input('application_deadline','Application deadline',p.application_deadline,'date',false)}${input('internship_type','Internship type',p.internship_type||'INTERNSHIP')}${input('location','Location',p.location,'text',false)}${select('work_mode','Work mode',['REMOTE','HYBRID','ONSITE'],p.work_mode||'REMOTE')}${input('positions','Positions',p.positions||1,'number',true,'min="1" max="10000"')}${select('status','Status',['DRAFT','PUBLISHED','CLOSED','ARCHIVED',...(p.status==='ACTIVE'?['ACTIVE']:[])],p.status||'DRAFT')}${select('applications_enabled','Accept applications',[['true','Yes'],['false','No']],String(p.applications_enabled||false))}</div>${text('description','Description',p.description)}${text('responsibilities','Responsibilities',p.responsibilities)}${text('skills','Skills / requirements',p.skills)}${text('eligibility','Eligibility',p.eligibility)}<button class="nc-button" type="submit">Save program</button><p class="nc-help">Published programs appear on the public internships page. Set Draft to unpublish, Closed to stop applications, or Archived to retire the program.</p></form>`;}
const profile=(p={})=>`${input('email','Email',p.email,'email')}<div class="nc-form-grid">${input('full_name','Full name',p.full_name)}${['phone_number','college_name','university_name','course','specialization','registration_number'].map(k=>input(k,pretty(k),p[k],'text',false)).join('')}</div>`;
const internship=(i={})=>`<div class="nc-form-grid">${select('program_id','Program',programs.map(p=>[p.id,`${p.title} (${p.status})`]),i.program_id)}${input('role','Role',i.role)}${input('department','Department',i.department)}${input('start_date','Approved start date',i.start_date,'date')}${input('end_date','Approved end date',i.end_date,'date')}${input('mentor','Supervisor',i.mentor,'text',false)}${input('project','Project',i.project,'text',false)}</div>`;
function documents(i,area='admin') {return `<section class="nc-panel nc-section"><h2>Documents</h2>${[['Offer Letter','offer_number','offer_status','offer_issued_at','offer-pdf','verify-offer'],['Certificate','certificate_number','certificate_status','issued_at','pdf','verify-certificate']].map(([title,num,status,issued,pdf,verify])=>`<div class="nc-document"><h3>${title} ${tag(i[status])}</h3>${i[num]?`<p class="nc-mono">${esc(i[num])}</p><p>Issued ${date(i[issued])}</p><div class="nc-actions">${i[status]==='VALID'?link('View',`/api/${area}/internships/${i.id}/${pdf}?view=1`)+link('Download PDF',`/api/${area}/internships/${i.id}/${pdf}`):''}${link('Verify',`/${verify}/${i[num]}`)}</div>`:'<p>Not issued yet.</p>'}</div>`).join('')}</section>`;}
async function internPage(id){
  const i=record=(await ctx.api(`/admin/internships/${id}`)).internship;
  const transitions={INVITED:['REGISTERED','APPROVED','REJECTED'],REGISTERED:['APPROVED','REJECTED'],APPROVED:['REJECTED'],OFFER_LETTER_ISSUED:['ACTIVE','TERMINATED'],ACTIVE:['COMPLETED','TERMINATED'],COMPLETED:['CERTIFICATE_ELIGIBLE','REJECTED'],CERTIFICATE_ELIGIBLE:['COMPLETED','REJECTED'],REJECTED:['APPROVED']};
  const labels={APPROVED:'Approve intern',ACTIVE:'Activate internship',COMPLETED:'Mark completed',CERTIFICATE_ELIGIBLE:'Approve certificate',REJECTED:'Reject',TERMINATED:'Terminate'};
  const history=(await ctx.api(`/admin/internships/${id}/history`)).history;
  shell(i.full_name,`${link('All interns','/admin/interns')}<div class="nc-columns nc-section"><section><div class="nc-panel">${tag(i.status)}<h2 class="nc-section">Personal & academic information</h2>${details([['Intern ID',i.id],['Email',i.email],['Phone',i.phone_number],['College',i.college_name],['University',i.university_name],['Course',i.course],['Specialization',i.specialization],['Registration',i.registration_number]])}<h2>Internship information</h2>${details([['Program',i.program_title],['Role',i.role],['Department',i.department],['Work mode',i.work_mode],['Start date',date(i.start_date)],['End date',date(i.end_date)],['Minimum duration',`${i.minimum_duration_months} months`],['Supervisor',i.mentor],['Project',i.project],['Eligible from',date(i.eligible_date)]])}${!i.offer_number&&!i.certificate_number?`<details><summary>Edit internship information</summary><form class="nc-form" data-admin-form="intern-edit">${internship(i)}<p>Saving clears prior approval.</p><button class="nc-button">Save changes</button></form></details>`:''}</div>${documents(i)}</section><aside><section class="nc-panel"><h2>Review & approval</h2><p>${i.duration_met?'The approved internship period has elapsed. Review successful completion before approving the certificate.':'Completion and certificate approval remain locked until the full approved period has elapsed.'}</p><div class="nc-actions">${(transitions[i.status]||[]).map(s=>button(labels[s]||pretty(s),`status:${s}`)).join('')}${i.status==='APPROVED'?button('Issue offer letter','offer'):''}${i.eligible?button('Issue certificate','issue'):''}</div><details class="nc-section"><summary>Student access</summary><p>Share an invitation only with the verified student.</p>${button('Create private invitation','invite')}</details>${i.certificate_status==='VALID'?`<details class="nc-section"><summary>Certificate controls</summary>${button('Regenerate PDF','regenerate')}<form class="nc-form" data-admin-form="revoke">${input('reason','Reason for permanent revocation','','text',true,'minlength="5" maxlength="500"')}<button class="nc-button danger">Revoke certificate</button></form></details>`:''}${i.offer_status==='VALID'?`<details class="nc-section"><summary>Offer controls</summary><form class="nc-form" data-admin-form="offer-revoke">${input('reason','Reason for permanent revocation','','text',true,'minlength="5" maxlength="500"')}<button class="nc-button danger">Revoke offer</button></form></details>`:''}</section><section class="nc-panel nc-section"><h2>Timeline & audit history</h2><ol class="nc-history">${history.map(h=>`<li><strong>${esc(pretty(h.event))}</strong><time>${esc(new Date(h.created_at).toLocaleString())}</time><small>Actor ${esc(h.actor_id||'System')}</small>${h.metadata.reason?`<p>${esc(h.metadata.reason)}</p>`:''}</li>`).join('')}</ol>${link('Full audit log','/admin/audit-logs')}</section></aside></div>`);
}
function templateForm(t){const p=t.draft;return `<form class="nc-form" data-admin-form="template" data-id="${t.id}" data-revision="${t.revision}" data-kind="${t.kind}">${input('name','Template name',t.name)}${input('title','Title',p.title)}${input('subtitle','Subtitle',p.subtitle,'text',false)}${text('body','Body text',p.body,1200)}${text('terms','Terms',p.terms)}${input('footer','Footer',p.footer,'text',false)}<div class="nc-form-grid">${select('font','Font',['NOTO_SANS','NOTO_SERIF'],p.font)}${input('title_size','Title size',p.title_size,'number',true,'min="18" max="34"')}${input('body_size','Body size',p.body_size,'number',true,'min="10" max="14"')}${select('logo_position','Logo position',['LEFT','RIGHT'],p.logo_position)}${select('signature_position','Signature position',['LEFT','RIGHT'],p.signature_position)}${select('qr_position','QR position',['LEFT','RIGHT'],p.qr_position)}${select('border','Border',['NONE','LINE','DOUBLE'],p.border)}${select('orientation','A4 orientation',[t.kind==='OFFER'?'PORTRAIT':'LANDSCAPE'],p.orientation)}${input('spacing','Line spacing',p.spacing,'number',true,'min="14" max="22"')}</div><div class="nc-actions"><button class="nc-button">Save draft</button>${button('Live preview','preview')}${['activate','deactivate','duplicate','reset'].map(a=>button(pretty(a),`template:${a}`)).join('')}</div><p class="nc-help">Save changes before activation. Published revisions are separate from drafts. Previously issued PDFs retain their original design. The signature is shown only on issued documents.</p><div class="nc-template-preview" aria-live="polite"></div></form>`;}
export async function mountAdmin(context){
  ctx=context;
  if(!ctx.root.dataset.adminEvents){ctx.root.addEventListener('submit',submit);ctx.root.addEventListener('click',action);ctx.root.dataset.adminEvents='true';}
  await render();
}
async function render(){
  const route=location.pathname.replace(/^\/admin\/?/,'').replace(/\/$/,''),q=new URLSearchParams(location.search);
  programs=(await ctx.api('/admin/programs')).programs;
  if(!route||route==='login'||route==='dashboard'){
    if(route!=='dashboard') history.replaceState(null,'','/admin/dashboard');
    const d=await ctx.api('/admin/dashboard');
    shell('A clear view of every internship.',`<p class="nc-lead">Manage the journey from application to verified achievement.</p><div class="nc-stats">${[['total','Total interns'],['active','Active interns'],['completed','Completed internships'],['eligible','Certificates eligible'],['issued','Certificates issued'],['offers','Offer letters issued'],['revoked','Revoked certificates'],['programs','Active programs']].map(([k,l])=>`<div class="nc-stat"><strong>${d.counts[k]}</strong><span>${l}</span></div>`).join('')}</div><div class="nc-actions">${link('Create intern','/admin/interns?new=1')}${link('Manage programs','/admin/internships/programs')}</div><h2 class="nc-section">Recent interns</h2>${internTable(d.recent)}<h2 class="nc-section">Recently issued documents</h2>${table(['Document','Intern','Issued','Record'],d.documents.map(d=>[`${esc(pretty(d.kind))}<small>${esc(d.number)}</small>`,esc(d.student_name),date(d.issued_at),link('Open',`/admin/interns/${d.internship_id}`)]))}<h2 class="nc-section">Upcoming completions · next 30 days</h2>${internTable(d.upcoming)}`);
  } else if(route==='internships/programs') shell('Internship programs',`<details class="nc-panel" ${programs.length?'':'open'}><summary>Create a program</summary>${programForm()}</details><div class="nc-section">${programs.map(p=>`<details class="nc-panel nc-section"><summary>${esc(p.title)} · ${esc(p.status)}</summary>${programForm(p)}${link('Public program',`/internships/${p.slug}`)}</details>`).join('')}</div>`);
  else if(route.startsWith('interns/')) await internPage(route.split('/')[1]);
  else if(route==='interns'&&q.has('new')) shell('Register an intern',`<form class="nc-form nc-panel" data-admin-form="intern-create"><h2>Student information</h2><p>Existing students are matched by email and keep their saved profile.</p>${profile()}<h2>Company-approved internship</h2>${internship()}<button class="nc-button">Create intern</button></form>`);
  else if(route==='interns') {
    const result=await ctx.api(`/admin/interns?${q}`);
    shell('Interns',`${link('Create intern','/admin/interns?new=1')}<form class="nc-form nc-panel nc-section" data-admin-form="filter"><div class="nc-form-grid">${input('search','Search name, email, ID or college',q.get('search'),'search',false)}${select('program_id','Program',[['','All programs'],...programs.map(p=>[p.id,p.title])],q.get('program_id'))}${select('status','Status',['','INVITED','REGISTERED','APPROVED','OFFER_LETTER_ISSUED','ACTIVE','COMPLETED','CERTIFICATE_ELIGIBLE','CERTIFICATE_ISSUED','REJECTED','TERMINATED','CERTIFICATE_REVOKED'],q.get('status'))}${select('certificate_status','Certificate',['','NONE','VALID','REVOKED'],q.get('certificate_status'))}${select('offer_status','Offer letter',['','NONE','VALID','REVOKED'],q.get('offer_status'))}${input('start_date','Start date',q.get('start_date'),'date',false)}${input('end_date','Completion date',q.get('end_date'),'date',false)}</div><button class="nc-button">Apply filters</button></form><p>${result.total} matching records</p>${internTable(result.internships,true)}${pagination(result.internships.length)}`);
  } else if(route==='applications') {
    const result=await ctx.api(`/admin/applications?${q}`);
    shell('Applications',result.applications.map(a=>{const p=programs.find(p=>p.id===a.program_id)||{};return `<details class="nc-panel nc-section"><summary>${esc(a.profile.full_name)} · ${esc(a.program_title)} · ${esc(a.status)}</summary>${details([['Email',a.email],...Object.entries(a.profile).map(([k,v])=>[pretty(k),v]),['Motivation',a.motivation]])}${a.internship_id?link('Open intern',`/admin/interns/${a.internship_id}`):`<form class="nc-form" data-admin-form="application" novalidate data-id="${a.id}">${select('status','Decision',['UNDER_REVIEW','REJECTED','ACCEPTED'],a.status)}<p>For acceptance, confirm the dates and role below. Approval and offer issuance follow in the intern profile.</p>${internship({program_id:p.id,role:p.role,department:p.department,start_date:p.start_date,end_date:p.end_date})}<button class="nc-button">Save decision</button></form>`}</details>`;}).join('')||empty('No applications yet.'));ctx.root.querySelector('.nc-admin-main').insertAdjacentHTML('beforeend',pagination(result.applications.length));
  } else if(['offers','certificates'].includes(route)) {
    const result=await ctx.api(`/admin/${route}?${q}`),verify=route==='offers'?'verify-offer':'verify-certificate';
    shell(route==='offers'?'Offer letters':'Certificates',table(['Document ID','Intern / program','Status','Issued','Actions'],result.documents.map(d=>[esc(d.number),`${esc(d.student_name)}<small>${esc(d.program)}</small>`,tag(d.status),date(d.issued_at),`${link('Documents',`/admin/interns/${d.internship_id}`)} ${link('Verify',`/${verify}/${d.number}`)}`]))+pagination(result.documents.length));
  } else if(route==='templates') {
    const result=await ctx.api('/admin/templates');templates=result.templates;defaults=result.defaults;
    shell('Document templates',`<p class="nc-lead">Controlled text and layout. Every issued document keeps an immutable snapshot.</p><form class="nc-form nc-panel" data-admin-form="template-create"><div class="nc-form-grid">${input('name','Template name')}${select('kind','Document type',['CERTIFICATE','OFFER'])}</div><button class="nc-button">Create template</button></form><p class="nc-help nc-section">Available placeholders: ${result.placeholders.map(p=>`<code>{{${p}}}</code>`).join(' · ')}</p>${templates.map(t=>`<details class="nc-panel nc-section"><summary>${esc(t.name)} · ${esc(t.kind)} · ${t.active?'ACTIVE':'INACTIVE'} · Draft ${t.revision}</summary>${templateForm(t)}</details>`).join('')}`);
  } else if(route==='company-assets') {
    const d=await ctx.api('/admin/company-assets');shell('Company identity & assets',`<form class="nc-form nc-panel" data-admin-form="company"><div class="nc-form-grid">${Object.entries(d.company).map(([k,v])=>input(k,pretty(k),v,k==='website'?'url':'text',k!=='identifiers')).join('')}</div><button class="nc-button">Save company identity</button></form><div class="nc-columns nc-section">${['company_logo','authorized_signature'].map(name=>{const a=d.assets.find(a=>a.name===name);return `<form class="nc-form nc-panel" data-admin-form="asset" data-name="${name}"><h2>${pretty(name)}</h2><p>${a?`Configured · ${date(a.updated_at)} · ${a.size} bytes`:'Not uploaded'}</p>${a?`<p class="nc-mono nc-help">SHA256 ${esc(a.sha256)}</p>`:''}<p>PNG up to 500 KB, maximum 3000 × 3000 pixels. Signature data stays private and is embedded only in issued PDFs.</p><label class="nc-field"><span class="nc-label">PNG file</span><input type="file" name="file" accept="image/png" required></label><button class="nc-button">Upload ${pretty(name)}</button></form>`;}).join('')}</div>`);
  } else if(route==='audit-logs') {const d=await ctx.api(`/admin/audit-logs?${q}`);shell('Audit log',`<form class="nc-filter" data-admin-form="filter">${input('search','Event search',q.get('search'),'search',false)}<button class="nc-button">Search</button></form>${table(['Time','Event','Actor','Target / metadata'],d.logs.map(l=>[esc(new Date(l.created_at).toLocaleString()),esc(l.event),esc(l.actor_email||'System'),`${l.internship_id?link('Intern',`/admin/interns/${l.internship_id}`):''}<small>${esc(JSON.stringify(l.metadata))}</small>`]))}${pagination(d.logs.length)}`);}
  else if(route==='verification') shell('Verify an official document',`<div class="nc-columns"><section class="nc-panel"><h2>Certificate verification</h2><p>Check a certificate against the authoritative issuance record.</p>${link('Verify certificate','/verify-certificate')}</section><section class="nc-panel"><h2>Offer letter verification</h2><p>Check an offer letter and its current status.</p>${link('Verify offer letter','/verify-offer')}</section></div>`);
  else if(route==='settings') shell('Account settings',`<section class="nc-panel"><h2>Account security</h2><p>Passwords are hashed server-side. Changing your password ends every active session.</p>${ctx.passwordForm()}</section>`);
  else shell('Page not found',link('Dashboard','/admin/dashboard'));
}
function templateData(form){const {name,...config}=Object.fromEntries(new FormData(form));for(const k of ['title_size','body_size','spacing'])config[k]=Number(config[k]);return {name,config,revision:Number(form.dataset.revision)};}
function showInvitation(result){ctx.message('Internship saved.','success');if(result.invitation_url)document.querySelector('#nc-message').insertAdjacentHTML('beforeend',`<p>Private invitation — share only with the verified student:</p><p class="nc-invite">${esc(result.invitation_url)}</p>${result.internship?link('Open intern',`/admin/interns/${result.internship.id}`):''}`);}
async function submit(event){const f=event.target.closest('[data-admin-form]');if(!f)return;event.preventDefault();if(f.dataset.busy)return;f.dataset.busy='1';const buttons=[...f.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const v=Object.fromEntries(new FormData(f)),kind=f.dataset.adminForm;
  try{
    if(kind==='filter'){location.href=`${location.pathname}?${new URLSearchParams(v)}`;return;}
    if(kind==='program'){for(const k of ['duration_months','minimum_duration_months','positions'])v[k]=Number(v[k]);for(const k of ['start_date','end_date','application_deadline'])v[k]||=null;v.applications_enabled=v.applications_enabled==='true';v.certificate_template='nextora-v1';await ctx.api(`/admin/programs${f.dataset.id?'/'+f.dataset.id:''}`,{method:f.dataset.id?'PATCH':'POST',data:v});}
    else if(kind==='intern-create'){const {email,full_name,phone_number,college_name,university_name,course,specialization,registration_number,...internship}=v;const r=await ctx.api('/admin/interns',{method:'POST',data:{student:{email,full_name,phone_number,college_name,university_name,course,specialization,registration_number},internship}});if(r.invitation_url){f.reset();showInvitation(r);}else location.href=`/admin/interns/${r.internship.id}`;return;}
    else if(kind==='intern-edit')await ctx.api(`/admin/internships/${record.id}`,{method:'PATCH',data:v});
    else if(['revoke','offer-revoke'].includes(kind))await ctx.api(`/admin/internships/${record.id}/${kind}`,{method:'POST',data:v});
    else if(kind==='application'){const {status,...internship}=v;const r=await ctx.api(`/admin/applications/${f.dataset.id}`,{method:'PATCH',data:{status,...(status==='ACCEPTED'?{internship}:{})}});await render();if(r.invitation_url){showInvitation(r);return;}ctx.message('Application updated.','success');return;}
    else if(kind==='template-create')await ctx.api('/admin/templates',{method:'POST',data:v});
    else if(kind==='template')await ctx.api(`/admin/templates/${f.dataset.id}`,{method:'PATCH',data:templateData(f)});
    else if(kind==='company')await ctx.api('/admin/company-assets',{method:'PUT',data:v});
    else if(kind==='asset'){const file=f.elements.file.files[0];if(file.size>512000)throw new Error('Use a PNG under 500 KB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);await ctx.api('/admin/company-assets/upload',{method:'POST',data:{name:f.dataset.name,png_base64:btoa(binary)}});}
    await render();ctx.message('Saved successfully.','success');
  }catch(e){ctx.message(e.message);}finally{delete f.dataset.busy;buttons.forEach(b=>b.disabled=false);}
}
async function action(event){const b=event.target.closest('[data-admin-action]');if(!b||b.disabled)return;b.disabled=true;const a=b.dataset.adminAction,f=b.closest('form');
  try{
    if(a==='preview'){
      const r=await fetch('/api/admin/templates/preview',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':ctx.session.csrf_token},body:JSON.stringify({kind:f.dataset.kind,config:templateData(f).config})});
      if(!r.ok)throw new Error((await r.json()).error||'Preview failed.');if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(await r.blob());f.querySelector('.nc-template-preview').innerHTML=`<iframe title="Document preview" src="${previewURL}"></iframe><a class="nc-link" href="${previewURL}" target="_blank" rel="noopener">Open preview in a new tab</a>`;return;
    }
    if(a.startsWith('template:'))await ctx.api(`/admin/templates/${f.dataset.id}/${a.split(':')[1]}`,{method:'POST',data:{revision:Number(f.dataset.revision)}});
    else if(a.startsWith('status:'))await ctx.api(`/admin/internships/${record.id}/status`,{method:'POST',data:{status:a.split(':')[1]}});
    else {const r=await ctx.api(`/admin/internships/${record.id}/${a}`,{method:'POST',data:{}});if(a==='invite'){showInvitation(r);return;}}
    await render();ctx.message('Record updated.','success');
  }catch(e){ctx.message(e.message);}finally{b.disabled=false;}
}
